title: Beyond Covers
description: "A website where typography on music albums is explained "
footer_text: Copyright 2021 Andreea Ruxandra Iancu
header_feature_image: ../uploads/lasttry.png
header_text: ""
header_text_color: "#ffffff"
bannerheight: 20vmax
navbarheight: 55px
logo: ../uploads/untitled-3.png
favicon: ../uploads/favicon-copy.ico
gridlayout: false
fixednavbar: true
upzoom: true
